### ISSUE TITLE
Add a 'interested' button to events in news feed

### ISSUE THREAD

**Issue by augustusarthur** [EnvironmentalDashboard/calendar#4]

**Comment by augustusarthur** [comment]
Update the code to not show click count till 10 people have clicked the 'I'm interested' button. Also, please take care of ajax? page shouldn't reload when the user clicks on the button after scrolling to an event way down.

**Comment by Terf** [comment]
Was addressed in a669c1baa334265f334ee7c374e9a022687506ab
